create database PSBAccessImprovement;
use PSBAccessImprovement;
show tables;

#simple proof of concept 

CREATE TABLE STUDENT (
    STUDENT_USERID CHAR(10) PRIMARY KEY,
    STUDENT_FIRST_NAME VARCHAR(255) NOT NULL,
    STUDENT_LAST_NAME VARCHAR(255) NOT NULL,
    STUDENT_EMAIL VARCHAR(255) NOT NULL,
    STUDENT_PASSWORD VARCHAR(255) NOT NULL,
    STUDENT_PROFILEPIC blob
);

CREATE TABLE COURSE (
    COURSE_ID INT PRIMARY KEY,
    STUDENT_USERID INT,
    COURSE_NAME VARCHAR(100),
    CLASS_TIME DATETIME,
    LOCATION VARCHAR(100),
    FOREIGN KEY (STUDENT_USERID) REFERENCES STUDENT(STUDENT_USERID)
);

CREATE TABLE TIMETABLE (
    TIMETABLE_ID INT PRIMARY KEY,
    STUDENT_USERID INT,
    COURSE_ID INT,
    COURSE_DAY VARCHAR(10),
    COURSE_TIME TIME,
    FOREIGN KEY (STUDENT_USERID) REFERENCES STUDENT(STUDENT_USERID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID INT PRIMARY KEY,
    STUDENT_USERID INT,
    COURSE_NAME VARCHAR(100),
    DUE_DATE DATETIME,
    description TEXT,
    FOREIGN KEY (STUDENT_USERID) REFERENCES STUDENTS(STUDENT_USERID)
);

CREATE TABLE STUDENT_COURSE (
    STUDENT_USERID CHAR(10) NOT NULL,
    COURSE_CODE VARCHAR(10) NOT NULL,
    PRIMARY KEY (STUDENT_USERID, COURSE_CODE),
    FOREIGN KEY (STUDENT_USERID) REFERENCES STUDENT(STUDENT_USERID),
    FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE)
);